// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID             int32
	ShortCode      string
	DestinationUrl string
	ClickCount     int32
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}
